# Generated by Django 3.2 on 2023-07-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20230724_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='article.Category', verbose_name='عکس جاری'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=False, verbose_name='انشارشود ؟ '),
        ),
    ]
